package main

// The byte encoder: assembly text to machine code.
//
// This is the first half of removing MinGW. x64.go already writes
// assembly under a rule that made this possible - one instruction per
// line, no macros, no pseudo-instructions, nothing the assembler has to
// evaluate - so every line here maps to exactly one encoding and there
// is nothing to interpret.
//
// It reads the text rather than a structured form on purpose. The text
// is generated by one function under a known style, so parsing it is
// reliable, and it means x64.go does not have to change at all: the
// assembly output stays the debugging tool it has always been, and this
// is a second consumer of it rather than a replacement.
//
// Correctness is not argued, it is checked. encode_test.go runs GNU as
// over the same text and compares the bytes, so the answer to "is this
// encoding right" is always the assembler's.

import (
	"fmt"
	"strconv"
	"strings"
)

// A reloc is a place in the code that needs an address filled in once
// everything has one.
type reloc struct {
	at     int    // byte offset of the 4-byte field
	sym    string // what it refers to
	next   int    // offset of the instruction after this one, for rel32
	isCall bool   // a call or jump, as opposed to a data reference
}

// An item is one instruction: either settled bytes, or a branch whose
// width is not decided yet.
type item struct {
	bytes []byte
	rel   []reloc // offsets within bytes, for a settled instruction

	// A branch to a label in this same block. Its width depends on how
	// far away the label turns out to be, which depends on the width of
	// every branch between here and there.
	branch bool
	esc    byte   // 0x0F for a conditional jump, 0 for jmp
	code   byte   // the near-form opcode
	target string // the label
	short  bool   // whether the two-byte form fits
}

// A block is encoded machine code plus what still has to be resolved.
//
// Instructions are held apart until the end because a branch can shrink.
// GNU as picks the two-byte form whenever the target is close enough,
// and shortening one branch moves everything after it, which can bring
// another branch into range. The loop below runs to a fixed point, which
// is what an assembler does and what makes the bytes here comparable to
// the assembler's.
type block struct {
	code   []byte // scratch for the instruction being encoded
	rel    []reloc
	items  []item
	at     map[string]int // label name to item index
	labels map[string]int // label name to byte offset, once settled
	relocs []reloc
}

// registers, in encoding order. The index is the number that goes into
// ModRM and REX.
var reg64 = []string{"rax", "rcx", "rdx", "rbx", "rsp", "rbp", "rsi", "rdi",
	"r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"}

var reg32 = []string{"eax", "ecx", "edx", "ebx", "esp", "ebp", "esi", "edi",
	"r8d", "r9d", "r10d", "r11d", "r12d", "r13d", "r14d", "r15d"}

var reg8 = []string{"al", "cl", "dl", "bl", "spl", "bpl", "sil", "dil",
	"r8b", "r9b", "r10b", "r11b", "r12b", "r13b", "r14b", "r15b"}

func regNum(name string, table []string) (int, bool) {
	for i, r := range table {
		if r == name {
			return i, true
		}
	}
	return 0, false
}

func xmmNum(name string) (int, bool) {
	if !strings.HasPrefix(name, "xmm") {
		return 0, false
	}
	n, err := strconv.Atoi(name[3:])
	if err != nil || n < 0 || n > 15 {
		return 0, false
	}
	return n, true
}

// An operand is one of a small set of shapes: a register, an immediate,
// a memory reference, or a symbol.
type operand struct {
	kind  int
	reg   int    // register number, for a register or a memory base
	index int    // second register in [base+index], or -1
	scale int    // 1, 2, 4 or 8, for [base+index*scale]
	disp  int64  // displacement, or the immediate
	sym   string // for sym[rip] and for a call target
	size  int    // 8, 32 or 64, for a register or a memory access
}

const (
	opReg = iota
	opXmm
	opImm
	opMem    // [base + disp] or [base + index]
	opRipSym // sym[rip]
	opSym    // a bare symbol, for call and jmp
)

// parseOperand reads one operand out of the text.
func parseOperand(s string) (operand, error) {
	s = strings.TrimSpace(s)

	// Memory, with or without a size prefix.
	size := 64
	for _, p := range []struct {
		text string
		bits int
	}{{"qword ptr ", 64}, {"dword ptr ", 32}, {"byte ptr ", 8}} {
		if strings.HasPrefix(s, p.text) {
			size = p.bits
			s = strings.TrimPrefix(s, p.text)
			break
		}
	}

	if strings.HasSuffix(s, "]") {
		open := strings.IndexByte(s, '[')
		if open < 0 {
			return operand{}, fmt.Errorf("malformed memory operand %q", s)
		}
		label := s[:open]
		inner := s[open+1 : len(s)-1]

		// sym[rip] and sym[rip+N] are both rip-relative references to a
		// symbol; the offset is folded into the addend.
		if label != "" {
			base := strings.TrimSpace(inner)
			var extra int64
			if plus := strings.IndexByte(base, '+'); plus >= 0 {
				n, err := strconv.ParseInt(strings.TrimSpace(base[plus+1:]), 0, 64)
				if err != nil {
					return operand{}, err
				}
				extra = n
				base = strings.TrimSpace(base[:plus])
			}
			if base != "rip" {
				return operand{}, fmt.Errorf("only rip-relative symbols are encoded, got %q", s)
			}
			return operand{kind: opRipSym, sym: label, disp: extra, size: size}, nil
		}

		return parseMem(inner, size)
	}

	if n, ok := regNum(s, reg64); ok {
		return operand{kind: opReg, reg: n, size: 64}, nil
	}
	if n, ok := regNum(s, reg32); ok {
		return operand{kind: opReg, reg: n, size: 32}, nil
	}
	if n, ok := regNum(s, reg8); ok {
		return operand{kind: opReg, reg: n, size: 8}, nil
	}
	if n, ok := xmmNum(s); ok {
		return operand{kind: opXmm, reg: n, size: 64}, nil
	}

	if n, err := strconv.ParseInt(s, 0, 64); err == nil {
		return operand{kind: opImm, disp: n}, nil
	}
	// A negative or very large literal that ParseInt read as unsigned.
	if n, err := strconv.ParseUint(s, 0, 64); err == nil {
		return operand{kind: opImm, disp: int64(n)}, nil
	}

	return operand{kind: opSym, sym: s}, nil
}

// parseMem reads what is inside the brackets: a base, optionally plus or
// minus a displacement, or a base plus an index register.
func parseMem(inner string, size int) (operand, error) {
	inner = strings.TrimSpace(inner)
	op := operand{kind: opMem, index: -1, scale: 1, size: size}

	sign := int64(1)
	cut := -1
	for i := 0; i < len(inner); i++ {
		if inner[i] == '+' || inner[i] == '-' {
			cut = i
			if inner[i] == '-' {
				sign = -1
			}
			break
		}
	}

	base := inner
	rest := ""
	if cut >= 0 {
		base = strings.TrimSpace(inner[:cut])
		rest = strings.TrimSpace(inner[cut+1:])
	}

	n, ok := regNum(base, reg64)
	if !ok {
		return operand{}, fmt.Errorf("unknown base register %q", base)
	}
	op.reg = n

	if rest == "" {
		return op, nil
	}
	// An index register, optionally scaled: [rax+rcx*8].
	scale := int64(1)
	idxName := rest
	if star := strings.IndexByte(rest, '*'); star >= 0 {
		idxName = strings.TrimSpace(rest[:star])
		n, err := strconv.ParseInt(strings.TrimSpace(rest[star+1:]), 0, 64)
		if err != nil || (n != 1 && n != 2 && n != 4 && n != 8) {
			return operand{}, fmt.Errorf("bad scale in %q", rest)
		}
		scale = n
	}
	if idx, ok := regNum(idxName, reg64); ok {
		if sign < 0 {
			return operand{}, fmt.Errorf("cannot subtract an index register")
		}
		op.index = idx
		op.scale = int(scale)
		return op, nil
	}
	v, err := strconv.ParseInt(rest, 0, 64)
	if err != nil {
		return operand{}, err
	}
	op.disp = sign * v
	return op, nil
}
