package main

// x86-64 emission, GNU as with `.intel_syntax noprefix`.
//
// This file is the one that gets replaced when the compiler stops
// shelling out to an assembler and writes machine code itself. Nothing
// above it knows an x86 register exists, and nothing here decides
// anything about the program: it turns IR into instructions and that is
// all. Keeping that line clean is what makes the eventual swap a
// substitution rather than a rewrite.
//
// Two rules for anything added here, both aimed at that swap:
//
//   1. No assembler conveniences. No macros, no pseudo-instructions, no
//      expressions the assembler has to evaluate. Every line must map to
//      exactly one instruction whose bytes we could write ourselves.
//      Anything else is a debt payable at the worst moment.
//
//   2. One instruction per line, no folding. The assembler will happily
//      pick a shorter encoding for us; we should not come to depend on
//      it doing so, because the byte writer will not.
//
// Register strategy is deliberately the dumbest correct one: every
// virtual register lives in a stack slot, and operands are loaded into
// rax and rcx around each instruction. That is slow, and it is also
// obviously right, which matters more while the pipeline is being
// proven. A real allocator replaces regAddr and nothing else.

import (
	"fmt"
	"strings"
)

type Emitter struct {
	b strings.Builder
	f *Func
}

// Windows x64 wants 32 bytes of shadow space reserved by the caller for
// the callee to spill rcx/rdx/r8/r9 into, whether or not it uses them.
const shadowSpace = 32

func (e *Emitter) line(format string, args ...any) {
	fmt.Fprintf(&e.b, "    "+format+"\n", args...)
}

func (e *Emitter) label(name string) {
	fmt.Fprintf(&e.b, "%s:\n", name)
}

func (e *Emitter) comment(text string) {
	fmt.Fprintf(&e.b, "    # %s\n", text)
}

// regAddr is where a virtual register lives. Every one gets its own slot
// below the frame pointer, after the local variable slots.
func (e *Emitter) regAddr(r Reg) string {
	off := (int(r) + e.f.NSlots + 1) * 8
	return fmt.Sprintf("qword ptr [rbp-%d]", off)
}

// slotAddr is where a Veyl local lives.
func (e *Emitter) slotAddr(slot int64) string {
	off := (int(slot) + 1) * 8
	return fmt.Sprintf("qword ptr [rbp-%d]", off)
}

// frameSize is the space for every local and every virtual register,
// rounded so that rsp stays 16-byte aligned at each call. The ABI
// requires that alignment and violating it crashes inside printf rather
// than anywhere near the mistake.
func (e *Emitter) frameSize() int {
	n := (e.f.NSlots + e.f.NRegs) * 8
	n += shadowSpace
	if n%16 != 0 {
		n += 16 - n%16
	}
	return n
}

func Emit(f *Func) string {
	e := &Emitter{f: f}

	e.b.WriteString("# Generated by veylasm. Do not edit.\n")
	e.b.WriteString("    .intel_syntax noprefix\n")
	e.b.WriteString("    .global main\n")
	e.b.WriteString("    .extern printf\n")
	e.b.WriteString("    .extern _setmode\n")
	e.b.WriteString("\n    .section .rdata\n")
	e.label("__fmt_int")
	e.b.WriteString("    .asciz \"%lld\\n\"\n")
	e.label("__fmt_str")
	e.b.WriteString("    .asciz \"%s\\n\"\n")
	e.label("__str_true")
	e.b.WriteString("    .asciz \"true\"\n")
	e.label("__str_false")
	e.b.WriteString("    .asciz \"false\"\n")
	e.b.WriteString("\n    .text\n")
	e.label("main")

	// Prologue. rbp is callee-saved, so it is pushed before being used
	// as the frame pointer, and restored on the way out.
	e.comment("prologue")
	e.line("push rbp")
	e.line("mov rbp, rsp")
	e.line("sub rsp, %d", e.frameSize())

	// Put stdout in binary mode. The C runtime otherwise translates every
	// \n into \r\n on the way out, so the same program printed CRLF here
	// and LF through the Go backend. The differential test against
	// ../src caught that on the first program ever compiled; without it
	// the two backends would have disagreed invisibly forever.
	// 1 is stdout, 0x8000 is _O_BINARY.
	e.comment("stdout to binary mode, so newlines match the Go backend")
	e.line("mov ecx, 1")
	e.line("mov edx, 32768")
	e.line("call _setmode")

	for _, in := range f.Code {
		e.instr(in)
	}

	e.comment("epilogue")
	e.line("xor eax, eax")
	e.line("mov rsp, rbp")
	e.line("pop rbp")
	e.line("ret")

	return e.b.String()
}

func (e *Emitter) instr(in Instr) {
	if in.Comment != "" {
		e.comment(in.Comment)
	}

	switch in.Op {
	case OpConst:
		// movabs, because a 64-bit immediate does not fit the plain form.
		e.line("mov rax, %d", in.Imm)
		e.line("mov %s, rax", e.regAddr(in.Dst))

	case OpLoad:
		e.line("mov rax, %s", e.slotAddr(in.Imm))
		e.line("mov %s, rax", e.regAddr(in.Dst))

	case OpStore:
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("mov %s, rax", e.slotAddr(in.Imm))

	case OpAdd, OpSub, OpMul:
		mnemonic := map[Op]string{OpAdd: "add", OpSub: "sub", OpMul: "imul"}[in.Op]
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("mov rcx, %s", e.regAddr(in.B))
		e.line("%s rax, rcx", mnemonic)
		e.line("mov %s, rax", e.regAddr(in.Dst))

	case OpDiv, OpMod:
		// idiv divides rdx:rax and is the one instruction here with
		// fixed register operands. cqo sign-extends rax into rdx first;
		// without it a negative dividend divides by a garbage high half.
		// Quotient lands in rax, remainder in rdx.
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("mov rcx, %s", e.regAddr(in.B))
		e.line("cqo")
		e.line("idiv rcx")
		if in.Op == OpDiv {
			e.line("mov %s, rax", e.regAddr(in.Dst))
		} else {
			e.line("mov %s, rdx", e.regAddr(in.Dst))
		}

	case OpNeg:
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("neg rax")
		e.line("mov %s, rax", e.regAddr(in.Dst))

	case OpEq, OpNe, OpLt, OpLe, OpGt, OpGe:
		// cmp sets the flags; setcc turns one flag combination into a
		// single 0 or 1 byte. setcc only writes 8 bits, so the register
		// is zeroed first - otherwise the upper 56 bits keep whatever
		// the last operation left there, and a "true" compares unequal
		// to 1. The zeroing must come before cmp, because xor writes
		// flags of its own.
		//
		// The signed forms (l/le/g/ge) are correct because Veyl integers
		// are signed. An unsigned type would need b/be/a/ae instead.
		cc := map[Op]string{
			OpEq: "e", OpNe: "ne", OpLt: "l", OpLe: "le", OpGt: "g", OpGe: "ge",
		}[in.Op]
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("mov rcx, %s", e.regAddr(in.B))
		e.line("xor edx, edx")
		e.line("cmp rax, rcx")
		e.line("set%s dl", cc)
		e.line("mov %s, rdx", e.regAddr(in.Dst))

	case OpNot:
		// !x is x == 0.
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("xor edx, edx")
		e.line("test rax, rax")
		e.line("sete dl")
		e.line("mov %s, rdx", e.regAddr(in.Dst))

	case OpLabel:
		e.label(fmt.Sprintf(".L%d", in.Imm))

	case OpJump:
		e.line("jmp .L%d", in.Imm)

	case OpJumpIf:
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("test rax, rax")
		e.line("jne .L%d", in.Imm)

	case OpJumpNot:
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("test rax, rax")
		e.line("je .L%d", in.Imm)

	case OpPrintInt:
		// Windows x64: first two integer arguments in rcx and rdx. The
		// shadow space is already part of the frame, so rsp needs no
		// adjustment here.
		e.line("lea rcx, __fmt_int[rip]")
		e.line("mov rdx, %s", e.regAddr(in.A))
		e.line("call printf")

	case OpPrintBool:
		// cmov rather than a branch: it picks between the two string
		// pointers with no jump, which keeps this to one basic block.
		// The false pointer is loaded first so that cmovne can overwrite
		// it, since cmov cannot take an address operand as its source.
		e.line("mov rax, %s", e.regAddr(in.A))
		e.line("lea rcx, __str_false[rip]")
		e.line("lea rdx, __str_true[rip]")
		e.line("test rax, rax")
		e.line("cmovne rcx, rdx")
		e.line("mov rdx, rcx")
		e.line("lea rcx, __fmt_str[rip]")
		e.line("call printf")

	default:
		e.comment(fmt.Sprintf("unhandled op %s", in.Op))
	}
}
