" Generated by 'veyl editors'. Do not edit: re-run it instead.
" Vim syntax file for the Veyl programming language.

if exists("b:current_syntax")
  finish
endif

syn keyword veylKeyword break const continue defer else false fn for if impl import in
syn keyword veylKeyword let match nil own pub return self step struct true unsafe while

syn keyword veylType int float str bool bytes void

syn keyword veylNamespace args bits bytes csv hash http json log mem net os rand
syn keyword veylNamespace re stats task term time url win zip

syn keyword veylBuiltin E INF NAN PI abs acos all any asin atan atan2 beep
syn keyword veylBuiltin cbrt ceil charAt chars clamp clear contains cos count divf each endsWith
syn keyword veylBuiltin errorOf exit exp fail failed filter find first float floor has hideConsole
syn keyword veylBuiltin hypot indexOf input insert int isFloat isInt isNan isOk isWin11 join keys
syn keyword veylBuiltin last len lines log log10 log2 lower map max messageBox min mod
syn keyword veylBuiltin must ok openWindow padLeft padRight pause pop pow print push random randomInt
syn keyword veylBuiltin reduce remove removeAt repeat replace reverse round setTitle sign sin sleep slice
syn keyword veylBuiltin sort sortBy split sqrt startsWith str substr sum tan toFloat toInt trim
syn keyword veylBuiltin trunc upper valueOr values winBuild write

syn match   veylNumber   "\v<0[xX][0-9a-fA-F_]+>"
syn match   veylNumber   "\v<0[bB][01_]+>"
syn match   veylNumber   "\v<[0-9][0-9_]*(\.[0-9][0-9_]*)?>"

syn region  veylString   start=/"/ skip=/\\./ end=/"/ contains=veylEscape,veylInterp
syn region  veylRawStr   start=/`/ end=/`/
syn match   veylEscape   /\\./ contained
syn region  veylInterp   start=/{/ end=/}/ contained contains=ALLBUT,veylInterp

syn match   veylComment  "//.*$"
" 'contains=veylBlock' is what makes block comments nest.
syn region  veylBlock    start="/\*" end="\*/" contains=veylBlock

hi def link veylKeyword    Keyword
hi def link veylType       Type
hi def link veylNamespace  Identifier
hi def link veylBuiltin    Function
hi def link veylNumber     Number
hi def link veylString     String
hi def link veylRawStr     String
hi def link veylEscape     SpecialChar
hi def link veylInterp     Special
hi def link veylComment    Comment
hi def link veylBlock      Comment

let b:current_syntax = "veyl"
