package main

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// `veyl editors <dir>` writes syntax definitions for the editors Veyl
// supports.
//
// They are generated rather than written by hand for the same reason
// `veyl builtins` exists: there are 300-odd builtins and 24 Keywords,
// and a list transcribed into four different file formats would be
// wrong within a week. Here the compiler's own tables are the source,
// so a builtin added to lib_bytes.go is highlighted everywhere as soon
// as this is re-run.
//
// The VS Code grammar is not generated. It is a TextMate grammar with
// hand-tuned patterns for interpolation and nested comments, which is
// real work that a table cannot express.

func runEditors(args []string) error {
	dir := "editors"
	if len(args) > 0 {
		dir = args[0]
	}

	writers := []struct {
		path  string
		build func() ([]byte, error)
	}{
		{filepath.Join(dir, "notepad++", "veyl.xml"), notepadPlusPlusUDL},
		{filepath.Join(dir, "sublime", "Veyl.sublime-syntax"), sublimeSyntax},
		{filepath.Join(dir, "vim", "syntax", "veyl.vim"), vimSyntax},
		{filepath.Join(dir, "vim", "ftdetect", "veyl.vim"), vimFiletype},
	}

	for _, w := range writers {
		body, err := w.build()
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(w.path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(w.path, body, 0o644); err != nil {
			return err
		}
		fmt.Printf("wrote %s\n", w.path)
	}
	return nil
}

// keywordList is every reserved word, sorted so the generated files do
// not churn between runs over Go's random map order.
func keywordList() []string {
	out := make([]string, 0, len(Keywords))
	for k := range Keywords {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// builtinNames splits the library into bare names and dotted paths.
// Editors highlight the two differently: a bare name is a function, a
// dotted one reads as a namespace and a member.
func builtinNames() (bare, dotted []string) {
	for name := range builtins {
		if strings.Contains(name, ".") {
			dotted = append(dotted, name)
		} else {
			bare = append(bare, name)
		}
	}
	for name := range builtinConsts {
		bare = append(bare, name)
	}
	sort.Strings(bare)
	sort.Strings(dotted)
	return bare, dotted
}

// namespaceNames are the library roots: os, http, bytes and the rest.
func namespaceNames() []string {
	out := make([]string, 0, len(namespaces))
	for n := range namespaces {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

const typeWords = "int float str bool bytes void"

// ---------------------------------------------------------------------
// Notepad++
//
// A "user defined language" is a single XML file dropped into the
// userDefineLangs folder. It has no grammar engine: you hand it lists
// of words and delimiters and it does the rest, which is why only the
// bare builtins go in. A dotted path would need a real tokeniser.

type udlKeywords struct {
	XMLName xml.Name `xml:"Keywords"`
	Name    string   `xml:"name,attr"`
	Value   string   `xml:",chardata"`
}

func notepadPlusPlusUDL() ([]byte, error) {
	bare, _ := builtinNames()

	// Notepad++ caps a keyword list at 30k characters. Three hundred
	// builtins is nowhere near it, but truncating silently would be a
	// miserable thing to debug, so it is worth being explicit.
	const maxList = 30000
	joined := strings.Join(bare, " ")
	if len(joined) > maxList {
		return nil, fmt.Errorf("the builtin list is %d characters, over Notepad++'s %d limit",
			len(joined), maxList)
	}

	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by 'veyl editors'. Do not edit: re-run it instead. -->
<NotepadPlus>
    <UserLang name="Veyl" ext="vy" udlVersion="2.1">
        <Settings>
            <Global caseIgnored="no" allowFoldOfComments="yes" foldCompact="no" />
            <Prefix Keywords1="no" Keywords2="no" Keywords3="no" Keywords4="no" />
        </Settings>
        <KeywordLists>
            <Keywords name="Comments">00// 01 02 03/* 04*/</Keywords>
            <Keywords name="Numbers, prefix1">0x</Keywords>
            <Keywords name="Numbers, prefix2">0b</Keywords>
            <Keywords name="Numbers, extras1">_</Keywords>
            <Keywords name="Operators1">+ - * / % = &lt; &gt; ! &amp; | ^ ~ ? : . , ( ) [ ] { }</Keywords>
`)
	fmt.Fprintf(&b, "            <Keywords name=\"Keywords1\">%s</Keywords>\n",
		xmlEscape(strings.Join(keywordList(), " ")))
	fmt.Fprintf(&b, "            <Keywords name=\"Keywords2\">%s</Keywords>\n",
		xmlEscape(typeWords))
	fmt.Fprintf(&b, "            <Keywords name=\"Keywords3\">%s</Keywords>\n",
		xmlEscape(joined))
	fmt.Fprintf(&b, "            <Keywords name=\"Keywords4\">%s</Keywords>\n",
		xmlEscape(strings.Join(namespaceNames(), " ")))
	b.WriteString(`            <Keywords name="Delimiters">00&quot; 01\ 02&quot; 03` + "`" + ` 04 05` + "`" + `</Keywords>
        </KeywordLists>
        <Styles>
            <WordsStyle name="DEFAULT" fgColor="D4D4D4" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="COMMENTS" fgColor="6A9955" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="LINE COMMENTS" fgColor="6A9955" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="NUMBERS" fgColor="B5CEA8" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="KEYWORDS1" fgColor="569CD6" bgColor="1E1E1E" fontStyle="1" />
            <WordsStyle name="KEYWORDS2" fgColor="4EC9B0" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="KEYWORDS3" fgColor="DCDCAA" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="KEYWORDS4" fgColor="C586C0" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="OPERATORS" fgColor="D4D4D4" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="DELIMITERS1" fgColor="CE9178" bgColor="1E1E1E" fontStyle="0" />
            <WordsStyle name="DELIMITERS2" fgColor="CE9178" bgColor="1E1E1E" fontStyle="0" />
        </Styles>
    </UserLang>
</NotepadPlus>
`)
	return []byte(b.String()), nil
}

func xmlEscape(s string) string {
	var b strings.Builder
	xml.EscapeText(&b, []byte(s))
	return b.String()
}

// ---------------------------------------------------------------------
// Sublime Text

func sublimeSyntax() ([]byte, error) {
	bare, _ := builtinNames()

	var b strings.Builder
	b.WriteString(`%YAML 1.2
---
# Generated by 'veyl editors'. Do not edit: re-run it instead.
name: Veyl
file_extensions: [vy]
scope: source.veyl

contexts:
  main:
    - include: comments
    - include: strings
    - include: numbers
    - include: Keywords
    - include: types
    - include: builtins

  comments:
    - match: //
      scope: punctuation.definition.comment.veyl
      push:
        - meta_scope: comment.line.double-slash.veyl
        - match: $\n?
          pop: true
    # Block comments nest, so the same rule pushes itself.
    - match: /\*
      scope: punctuation.definition.comment.veyl
      push:
        - meta_scope: comment.block.veyl
        - match: /\*
          push:
            - meta_scope: comment.block.veyl
            - match: \*/
              pop: true
        - match: \*/
          pop: true

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.veyl
      push:
        - meta_scope: string.quoted.double.veyl
        - match: '\\.'
          scope: constant.character.escape.veyl
        # Interpolation: any expression between braces.
        - match: '\{'
          scope: punctuation.section.interpolation.begin.veyl
          push:
            - meta_scope: meta.interpolation.veyl
            - clear_scopes: 1
            - match: '\}'
              scope: punctuation.section.interpolation.end.veyl
              pop: true
            - include: main
        - match: '"'
          scope: punctuation.definition.string.end.veyl
          pop: true
    - match: '` + "`" + `'
      scope: punctuation.definition.string.begin.veyl
      push:
        - meta_scope: string.quoted.other.raw.veyl
        - match: '` + "`" + `'
          scope: punctuation.definition.string.end.veyl
          pop: true

  numbers:
    - match: '\b0[xX][0-9a-fA-F_]+\b'
      scope: constant.numeric.hex.veyl
    - match: '\b0[bB][01_]+\b'
      scope: constant.numeric.binary.veyl
    - match: '\b[0-9][0-9_]*(\.[0-9][0-9_]*)?\b'
      scope: constant.numeric.veyl

`)
	fmt.Fprintf(&b, "  Keywords:\n    - match: '\\b(%s)\\b'\n      scope: keyword.control.veyl\n\n",
		strings.Join(keywordList(), "|"))
	fmt.Fprintf(&b, "  types:\n    - match: '\\b(%s)\\b'\n      scope: storage.type.veyl\n\n",
		strings.Join(strings.Fields(typeWords), "|"))
	fmt.Fprintf(&b, "  builtins:\n    - match: '\\b(%s)\\b'\n      scope: support.function.veyl\n",
		strings.Join(namespaceNames(), "|"))
	fmt.Fprintf(&b, "    - match: '\\b(%s)\\b'\n      scope: support.function.veyl\n",
		strings.Join(bare, "|"))
	return []byte(b.String()), nil
}

// ---------------------------------------------------------------------
// Vim and Neovim

func vimSyntax() ([]byte, error) {
	bare, _ := builtinNames()

	var b strings.Builder
	b.WriteString(`" Generated by 'veyl editors'. Do not edit: re-run it instead.
" Vim syntax file for the Veyl programming language.

if exists("b:current_syntax")
  finish
endif

`)
	// Vim chokes on very long lines, so the builtins are emitted in
	// batches rather than one enormous keyword command.
	writeKeywords := func(group string, words []string) {
		const perLine = 12
		for i := 0; i < len(words); i += perLine {
			end := i + perLine
			if end > len(words) {
				end = len(words)
			}
			fmt.Fprintf(&b, "syn keyword %s %s\n", group, strings.Join(words[i:end], " "))
		}
	}

	writeKeywords("veylKeyword", keywordList())
	b.WriteString("\n")
	writeKeywords("veylType", strings.Fields(typeWords))
	b.WriteString("\n")
	writeKeywords("veylNamespace", namespaceNames())
	b.WriteString("\n")
	writeKeywords("veylBuiltin", bare)

	b.WriteString(`
syn match   veylNumber   "\v<0[xX][0-9a-fA-F_]+>"
syn match   veylNumber   "\v<0[bB][01_]+>"
syn match   veylNumber   "\v<[0-9][0-9_]*(\.[0-9][0-9_]*)?>"

syn region  veylString   start=/"/ skip=/\\./ end=/"/ contains=veylEscape,veylInterp
syn region  veylRawStr   start=/` + "`" + `/ end=/` + "`" + `/
syn match   veylEscape   /\\./ contained
syn region  veylInterp   start=/{/ end=/}/ contained contains=ALLBUT,veylInterp

syn match   veylComment  "//.*$"
" 'contains=veylBlock' is what makes block comments nest.
syn region  veylBlock    start="/\*" end="\*/" contains=veylBlock

hi def link veylKeyword    Keyword
hi def link veylType       Type
hi def link veylNamespace  Identifier
hi def link veylBuiltin    Function
hi def link veylNumber     Number
hi def link veylString     String
hi def link veylRawStr     String
hi def link veylEscape     SpecialChar
hi def link veylInterp     Special
hi def link veylComment    Comment
hi def link veylBlock      Comment

let b:current_syntax = "veyl"
`)
	return []byte(b.String()), nil
}

func vimFiletype() ([]byte, error) {
	return []byte(`" Generated by 'veyl editors'. Do not edit: re-run it instead.
autocmd BufNewFile,BufRead *.vy set filetype=veyl
`), nil
}
