let s = "Hello, World"
print(upper(s))
print(lower(s))
print(substr(s, 0, 5))
print(substr(s, 7, 12))
print(indexOf(s, "World"))
print(indexOf(s, "zzz"))
print(contains(s, "lo, W"))
print(contains(s, "nope"))
print(startsWith(s, "Hello"))
print(startsWith(s, "World"))
print(endsWith(s, "World"))
print(endsWith(s, "Hello"))
print(repeat("ab", 3))
print(len(upper(s)))
print(substr(s, 100, 200))
print(upper("mixed 123 CASE"))
print(charAt("abc", 1))
